# External gems
gems:
 # - jekyll-archives # Sorry, not GitHub pages friendly!
  - jekyll-sitemap

exclude:
  - "/vendor/"

# Site settings
title: Barbara Caban
subtitle: Studiolop
email: barbaramolin2000@yahoo.com
name: Barbara Caban
description: Artist and designer
# Base URL of site (i.e. /blog). It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
baseurl: ""
# the base hostname & protocol for your site
url: ""
cover: "/assets/images/party-painting.jpg"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: false
permalink: pretty

uploads_dir: "assets/images"

# Image CDN
imagecdn:
  #staging: "http://ed-eyegallery-dev.imgix.net"
  production: "http://ed-studiolop.imgix.net"

# Collections Example
collections:
    gallery:
        output: true
        permalink: /gallery/:path/

# Defaults Example
defaults:
    -
        scope:
            path: ""
            type: "gallery"
        values:
            layout: "gallery"

# Disqus comments
# disqus_shortname:

# Google analytics
ga_tracking_id: "UA-16735011-16"


# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts
social:

  - name: Facebook
    icon: icon-facebook_sign
    username: Studiolop
    url: https://www.facebook.com/Studiolop-423264891118417/?fref=ts
    desc: Like on Facebook
    share: true

  - name: Instagram
    icon: icon-instagram
    username: studiolop
    url: https://www.instagram.com/studiolop/
    desc: Follow me on Instagram
    share: false

  - name: Twitter
    icon: icon-twitter_sign
    username: BarbaraCaban
    url: https://twitter.com/BarbaraCaban
    desc: Follow us on Twitter
    share: true

#Google Recaptcha for contact form

recaptcha_site_key: 6LdAWRQUAAAAAK1V7sKck5l5oOCytuUMp9xI3_ur

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "/assets/images/party-painting.jpg"
    fb_image_width: 640 # preferred 1024
    fb_image_height: 432 # preferred 307
    fb_image_type: "image/jpg"

    twitter_image: "/assets/images/party-painting.jpg"

